version: '3.9'

services:
  redis:
    image: redis:7.2.5-alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - ./app:/app

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "16379:6379"
      - "18001:8001"
    expose:
      - 16379
      - 18001

  app:
    build:
      context: .
    volumes:
      - ./app:/app
    command: sleep infinity
    environment:
      - REDIS_OM_URL=redis://@redis-stack:6379/0
